#6: Implemented DataHandler class and extract/remove/namelist
ecmwf-ifs/ifsbench pull request #7
Opened 2024-12-16 07:50 UTC by johannesbulin

(See issue #6)

Added support for data pipelines to `ifsbench`. The main feature is a `DataHandler` base class that can perform a given action on a working directory. Currently I've implemented:

- `RenameHandler` - for moving/renaming/copying files, using regular expressions.
- `NamelistHandler` - for modifying namelists.
- `ExtractHandler` - for extracting archives.

Talking points / request for feedback:

- At the moment, nothing in the data pipeline uses the `InputFile` concept that we've used before (with file hashes and other things). If you think that this should be included, I'd be happy about some suggestions.
- I am not a big fan of having enums as embedded classes (`RenameHandler.RenameMode` for example). It's a bit clunky to write but I haven't come up with a better solution.

2024-12-16 07:50 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ifsbench?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ifsbench?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/ifsbench?pullRequest=7) it.</sub>

2025-01-09 13:58 UTC, reuterbal requested changes
Thanks, this looks great already!

I left a lot of nitpicky comments but mostly around style and docstrings. Implementation looks mostly good to me and testing is very diligently done!

2025-01-09 13:58 UTC, reuterbal commented on ifsbench/data/namelisthandler.py
> +            debug(f"Set namelist entry {str(self._keys)} = {str(self._value)}.")
[Purely FYI, no action required] The following should be a string conversion shorthand for f-strings

```suggestion
            debug(f"Set namelist entry {self._keys!s} = {self._value!s}.")
```

2025-01-09 13:58 UTC, reuterbal commented on ifsbench/data/namelisthandler.py
> +        """
Move the Parameters section to the class docstring please

2025-01-09 13:58 UTC, reuterbal commented on ifsbench/data/namelisthandler.py
> +                raise ValueError("Namelist overrides must be NamelistOverride objects!")
You could use a list comprehension here:
```suggestion
        if not all(isinstance(override, NamelistOverride) for override in self._overrides):
            raise ValueError("Namelist overrides must be NamelistOverride objects!")
```

2025-01-09 13:58 UTC, reuterbal commented on ifsbench/data/renamehandler.py
> +        mode:   `RenameHandler.RenameMode`
```suggestion
        mode: RenameHandler.RenameMode
```

2025-01-09 13:58 UTC, reuterbal commented on tests/data/test_renamehandler.py
> +    ),
`repl` should not be an r-string, right?

Also, if you decide to allow also compiled patterns I would add or convert 1-2 of the parameterisations to use `re.compile(r'...')` as `pattern`

2025-01-10 13:57 UTC, johannesbulin commented on ifsbench/data/extracthandler.py
> +    def execute(self, wdir, **kwargs):
Does the `execute` function needs its own docstring? I thought that it would just inherit the docstring from the parent class `DataHandler`?!

2025-01-10 14:26 UTC, johannesbulin commented on ifsbench/data/renamehandler.py
> +        mode:   `RenameHandler.RenameMode`
Went for :class:`RenameMode`. Hope this is okay as well.

2025-01-10 14:29 UTC, johannesbulin commented on tests/data/test_renamehandler.py
> +    ),
Tried to change this but now it complains about repl strings that contain `\g<something>`. So I guess that at least some of them should should be r-strings.

2025-01-20 08:58 UTC, reuterbal approved these changes
Many thanks for making the suggested changes! Looks great to me now.

2025-01-20 08:58 UTC, reuterbal commented on ifsbench/data/extracthandler.py
> +    def execute(self, wdir, **kwargs):
Not sure if it works like this but fine with keeping it like this for now.

2025-01-20 10:47 UTC, merged